[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/claim-spin"
  to = "/.netlify/functions/claim-spin"
  status = 200

[[redirects]]
  from = "/api/admin-list-emails"
  to = "/.netlify/functions/admin-list-emails"
  status = 200
